"""Initial multi-tenant SaaS CRM schema

Revision ID: 92104dee2801
Revises: 
Create Date: 2026-05-27 09:25:54.369202

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '92104dee2801'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('subscription_plan', sa.String(length=100), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('storage_limit_mb', sa.Float(), nullable=True),
    sa.Column('storage_used_mb', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=False),
    sa.Column('field_key', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('validation_json', sa.JSON(), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('help_text', sa.String(length=500), nullable=True),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_fields_id'), 'custom_fields', ['id'], unique=False)
    op.create_index(op.f('ix_custom_fields_tenant_id'), 'custom_fields', ['tenant_id'], unique=False)
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_index(op.f('ix_forms_tenant_id'), 'forms', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_tenant_id'), 'universities', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_values_field_id'), 'custom_field_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_id'), 'custom_field_values', ['id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_record_id'), 'custom_field_values', ['record_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_tenant_id'), 'custom_field_values', ['tenant_id'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_required_override', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_field_id'), 'form_fields', ['field_id'], unique=False)
    op.create_index(op.f('ix_form_fields_form_id'), 'form_fields', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_fields_id'), 'form_fields', ['id'], unique=False)
    op.create_index(op.f('ix_form_fields_tenant_id'), 'form_fields', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('platform_super_admin', 'admin', 'counsellor', 'student', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_key', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_stages_id'), 'workflow_stages', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_tenant_id'), 'workflow_stages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_workflow_id'), 'workflow_stages', ['workflow_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_values_json', sa.JSON(), nullable=True),
    sa.Column('new_values_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('country_doc_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_doc_templates_country'), 'country_doc_templates', ['country'], unique=True)
    op.create_index(op.f('ix_country_doc_templates_id'), 'country_doc_templates', ['id'], unique=False)
    op.create_index(op.f('ix_country_doc_templates_tenant_id'), 'country_doc_templates', ['tenant_id'], unique=False)
    op.create_table('enquiry_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('intake_month', sa.String(length=50), nullable=True),
    sa.Column('intake_year', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_students_id'), 'enquiry_students', ['id'], unique=False)
    op.create_index(op.f('ix_enquiry_students_intake_month'), 'enquiry_students', ['intake_month'], unique=False)
    op.create_index(op.f('ix_enquiry_students_intake_year'), 'enquiry_students', ['intake_year'], unique=False)
    op.create_index(op.f('ix_enquiry_students_name'), 'enquiry_students', ['name'], unique=False)
    op.create_index(op.f('ix_enquiry_students_tenant_id'), 'enquiry_students', ['tenant_id'], unique=False)
    op.create_table('record_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('old_stage_id', sa.Integer(), nullable=True),
    sa.Column('new_stage_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_stage_id'], ['workflow_stages.id'], ),
    sa.ForeignKeyConstraint(['old_stage_id'], ['workflow_stages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_stage_history_id'), 'record_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_record_stage_history_record_id'), 'record_stage_history', ['record_id'], unique=False)
    op.create_index(op.f('ix_record_stage_history_tenant_id'), 'record_stage_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_record_stage_history_workflow_id'), 'record_stage_history', ['workflow_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('letzstudy_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('highest_education', sa.Enum('below_10th', 'tenth', 'twelfth', 'diploma', 'bachelor', 'master', 'phd', name='highesteducation'), nullable=True, comment="Student's highest completed education level; drives document checklist filter"),
    sa.Column('lead_status', sa.Enum('lead', 'hot', 'warm', 'cold', 'converted', 'lost', name='leadstatus'), nullable=True),
    sa.Column('counsellor_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('citizenship', sa.String(length=100), nullable=True),
    sa.Column('dual_citizenship', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mailing_address1', sa.String(length=255), nullable=True),
    sa.Column('mailing_address2', sa.String(length=255), nullable=True),
    sa.Column('mailing_city', sa.String(length=100), nullable=True),
    sa.Column('mailing_state', sa.String(length=100), nullable=True),
    sa.Column('mailing_country', sa.String(length=100), nullable=True),
    sa.Column('mailing_pincode', sa.String(length=20), nullable=True),
    sa.Column('same_as_mailing', sa.Boolean(), nullable=True),
    sa.Column('permanent_address1', sa.String(length=255), nullable=True),
    sa.Column('permanent_address2', sa.String(length=255), nullable=True),
    sa.Column('permanent_city', sa.String(length=100), nullable=True),
    sa.Column('permanent_state', sa.String(length=100), nullable=True),
    sa.Column('permanent_country', sa.String(length=100), nullable=True),
    sa.Column('permanent_pincode', sa.String(length=20), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('passport_issue_country', sa.String(length=100), nullable=True),
    sa.Column('passport_issue_date', sa.Date(), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('city_of_birth', sa.String(length=100), nullable=True),
    sa.Column('country_of_birth', sa.String(length=100), nullable=True),
    sa.Column('living_in_other_country', sa.Boolean(), nullable=True),
    sa.Column('living_country', sa.String(length=100), nullable=True),
    sa.Column('applied_for_immigration', sa.Boolean(), nullable=True),
    sa.Column('serious_medical_condition', sa.Boolean(), nullable=True),
    sa.Column('medical_condition_details', sa.Text(), nullable=True),
    sa.Column('visa_refusal', sa.Boolean(), nullable=True),
    sa.Column('visa_refusal_details', sa.Text(), nullable=True),
    sa.Column('visa_refusal_countries', sa.JSON(), nullable=True),
    sa.Column('criminal_conviction', sa.Boolean(), nullable=True),
    sa.Column('criminal_conviction_details', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_branch_id'), 'students', ['branch_id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_letzstudy_email'), 'students', ['letzstudy_email'], unique=True)
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_table('test_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_overall_score', sa.Boolean(), nullable=True),
    sa.Column('overall_score_label', sa.String(length=100), nullable=True),
    sa.Column('overall_score_min', sa.Float(), nullable=True),
    sa.Column('overall_score_max', sa.Float(), nullable=True),
    sa.Column('overall_score_step', sa.Float(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('has_expiry', sa.Boolean(), nullable=True),
    sa.Column('validity_years', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_test_types_id'), 'test_types', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('academic_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('tenth', 'twelfth', 'diploma', 'ug', 'pg', name='academiclevel'), nullable=False),
    sa.Column('is_highest', sa.Boolean(), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('board_university', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('percentage_cgpa', sa.Float(), nullable=True),
    sa.Column('grading_scale', sa.String(length=50), nullable=True),
    sa.Column('backlogs', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('degree_name', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('stream', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_qualifications_id'), 'academic_qualifications', ['id'], unique=False)
    op.create_index(op.f('ix_academic_qualifications_tenant_id'), 'academic_qualifications', ['tenant_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('intake_month', sa.String(length=50), nullable=True),
    sa.Column('representative', sa.String(length=255), nullable=True),
    sa.Column('intake_year', sa.Integer(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('course_start_date', sa.Date(), nullable=True),
    sa.Column('course_end_date', sa.Date(), nullable=True),
    sa.Column('course_duration_months', sa.Integer(), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('scholarship_amount', sa.Float(), nullable=True),
    sa.Column('campus_location', sa.String(length=255), nullable=True),
    sa.Column('delivery_mode', sa.String(length=255), nullable=True),
    sa.Column('student_id_on_letter', sa.String(length=255), nullable=True),
    sa.Column('application_fee', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(length=100), nullable=True),
    sa.Column('application_status', sa.Enum('pending_from_student', 'initiated', 'pending_from_LS', 'conditional_offer', 'unconditional_offer', 'case_closed', 'application_on_hold', 'funds_approved', 'offer_accepted', 'rejected', 'waitlisted', 'withdrawn', 'deferral', 'fee_paid', 'tuition_payment_not_done', 'visa_applied', 'visa_approved', 'visa_rejected', name='applicationstatus'), nullable=True),
    sa.Column('visa_status', sa.Enum('not_applied', 'visa_applied', 'visa_approved', 'visa_rejected', name='visastatus'), nullable=True),
    sa.Column('visa_applied_date', sa.Date(), nullable=True),
    sa.Column('visa_decision_date', sa.Date(), nullable=True),
    sa.Column('offer_letter_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status_reason', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_branch_id'), 'applications', ['branch_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_table('country_doc_template_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('marksheet_10', 'marksheet_12', 'diploma_cert', 'diploma_transcripts', 'ug_degree_cert', 'ug_degree_transcripts', 'ug_provisional_cert', 'transfer_cert', 'moi_cert', 'backlog_cert', 'masters_cert', 'masters_transcript', 'phd_cert', 'ielts', 'toefl', 'pte', 'duolingo', 'gre', 'gmat', 'sat', 'act', 'bank_statements', 'bank_balance_cert', 'fd_certs', 'education_loan', 'itr', 'salary_slips', 'employment_letter', 'gst_cert', 'business_reg', 'property_valuation', 'affidavit_support', 'passport', 'offer_letter', 'cas_i20_coe', 'visa_form', 'visa_fee_receipt', 'sevis_receipt', 'gta_sop', 'biometrics_confirmation', 'medical_report', 'pcc', 'travel_insurance', 'sop', 'lor', 'cv', 'portfolio', 'work_exp_letter', 'internship_cert', 'extracurricular_cert', 'passport_photo', 'other', name='documenttype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('academic', 'language', 'financial', 'visa', 'supporting', 'other', name='documentcategory'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['country_doc_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_doc_template_fields_id'), 'country_doc_template_fields', ['id'], unique=False)
    op.create_index(op.f('ix_country_doc_template_fields_template_id'), 'country_doc_template_fields', ['template_id'], unique=False)
    op.create_table('custom_profile_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'integer', 'float_', 'yes_no', 'long_text', 'dropdown', name='customfieldtype'), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=50), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('dropdown_options', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_profile_fields_id'), 'custom_profile_fields', ['id'], unique=False)
    op.create_table('document_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('marksheet_10', 'marksheet_12', 'diploma_cert', 'diploma_transcripts', 'ug_degree_cert', 'ug_degree_transcripts', 'ug_provisional_cert', 'transfer_cert', 'moi_cert', 'backlog_cert', 'masters_cert', 'masters_transcript', 'phd_cert', 'ielts', 'toefl', 'pte', 'duolingo', 'gre', 'gmat', 'sat', 'act', 'bank_statements', 'bank_balance_cert', 'fd_certs', 'education_loan', 'itr', 'salary_slips', 'employment_letter', 'gst_cert', 'business_reg', 'property_valuation', 'affidavit_support', 'passport', 'offer_letter', 'cas_i20_coe', 'visa_form', 'visa_fee_receipt', 'sevis_receipt', 'gta_sop', 'biometrics_confirmation', 'medical_report', 'pcc', 'travel_insurance', 'sop', 'lor', 'cv', 'portfolio', 'work_exp_letter', 'internship_cert', 'extracurricular_cert', 'passport_photo', 'other', name='documenttype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('academic', 'language', 'financial', 'visa', 'supporting', 'other', name='documentcategory'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_fields_id'), 'document_fields', ['id'], unique=False)
    op.create_table('enquiry_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry_students.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['enquiry_notes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_notes_enquiry_id'), 'enquiry_notes', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_enquiry_notes_id'), 'enquiry_notes', ['id'], unique=False)
    op.create_index(op.f('ix_enquiry_notes_tenant_id'), 'enquiry_notes', ['tenant_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_branch_id'), 'notes', ['branch_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_tenant_id'), 'notes', ['tenant_id'], unique=False)
    op.create_table('student_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['student_notes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_notes_id'), 'student_notes', ['id'], unique=False)
    op.create_index(op.f('ix_student_notes_tenant_id'), 'student_notes', ['tenant_id'], unique=False)
    op.create_table('student_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('test_prep', 'accommodation', 'flywire', 'loan', 'forex', 'visa_assistance', name='servicetype'), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_services_id'), 'student_services', ['id'], unique=False)
    op.create_index(op.f('ix_student_services_tenant_id'), 'student_services', ['tenant_id'], unique=False)
    op.create_table('test_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('test_type_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('section_scores', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scores_id'), 'test_scores', ['id'], unique=False)
    op.create_index(op.f('ix_test_scores_tenant_id'), 'test_scores', ['tenant_id'], unique=False)
    op.create_table('whatsapp_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('wa_id', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('is_opted_in', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_contacts_id'), 'whatsapp_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_contacts_phone_number'), 'whatsapp_contacts', ['phone_number'], unique=True)
    op.create_index(op.f('ix_whatsapp_contacts_student_id'), 'whatsapp_contacts', ['student_id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_id'), 'work_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_work_experiences_tenant_id'), 'work_experiences', ['tenant_id'], unique=False)
    op.create_table('application_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment_data', sa.LargeBinary(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_messages_id'), 'application_messages', ['id'], unique=False)
    op.create_index(op.f('ix_application_messages_tenant_id'), 'application_messages', ['tenant_id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['document_fields.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_files_id'), 'document_files', ['id'], unique=False)
    op.create_table('note_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_files_id'), 'note_files', ['id'], unique=False)
    op.create_index(op.f('ix_note_files_tenant_id'), 'note_files', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('manual_student_name', sa.String(length=255), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'partial', name='paymentstatus'), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payment_mode', sa.String(length=100), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('invoice_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('student_custom_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['custom_profile_fields.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'field_id', name='uq_student_field_value')
    )
    op.create_index(op.f('ix_student_custom_field_values_id'), 'student_custom_field_values', ['id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_mime_type', sa.String(length=100), nullable=True),
    sa.Column('media_data', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_contact_id'), 'whatsapp_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_created_at'), 'whatsapp_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_tenant_id'), 'whatsapp_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_wa_message_id'), 'whatsapp_messages', ['wa_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_wa_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_tenant_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_created_at'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_contact_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_student_custom_field_values_id'), table_name='student_custom_field_values')
    op.drop_table('student_custom_field_values')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_note_files_tenant_id'), table_name='note_files')
    op.drop_index(op.f('ix_note_files_id'), table_name='note_files')
    op.drop_table('note_files')
    op.drop_index(op.f('ix_document_files_id'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_application_messages_tenant_id'), table_name='application_messages')
    op.drop_index(op.f('ix_application_messages_id'), table_name='application_messages')
    op.drop_table('application_messages')
    op.drop_index(op.f('ix_work_experiences_tenant_id'), table_name='work_experiences')
    op.drop_index(op.f('ix_work_experiences_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_whatsapp_contacts_student_id'), table_name='whatsapp_contacts')
    op.drop_index(op.f('ix_whatsapp_contacts_phone_number'), table_name='whatsapp_contacts')
    op.drop_index(op.f('ix_whatsapp_contacts_id'), table_name='whatsapp_contacts')
    op.drop_table('whatsapp_contacts')
    op.drop_index(op.f('ix_test_scores_tenant_id'), table_name='test_scores')
    op.drop_index(op.f('ix_test_scores_id'), table_name='test_scores')
    op.drop_table('test_scores')
    op.drop_index(op.f('ix_student_services_tenant_id'), table_name='student_services')
    op.drop_index(op.f('ix_student_services_id'), table_name='student_services')
    op.drop_table('student_services')
    op.drop_index(op.f('ix_student_notes_tenant_id'), table_name='student_notes')
    op.drop_index(op.f('ix_student_notes_id'), table_name='student_notes')
    op.drop_table('student_notes')
    op.drop_index(op.f('ix_notes_tenant_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_branch_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_enquiry_notes_tenant_id'), table_name='enquiry_notes')
    op.drop_index(op.f('ix_enquiry_notes_id'), table_name='enquiry_notes')
    op.drop_index(op.f('ix_enquiry_notes_enquiry_id'), table_name='enquiry_notes')
    op.drop_table('enquiry_notes')
    op.drop_index(op.f('ix_document_fields_id'), table_name='document_fields')
    op.drop_table('document_fields')
    op.drop_index(op.f('ix_custom_profile_fields_id'), table_name='custom_profile_fields')
    op.drop_table('custom_profile_fields')
    op.drop_index(op.f('ix_country_doc_template_fields_template_id'), table_name='country_doc_template_fields')
    op.drop_index(op.f('ix_country_doc_template_fields_id'), table_name='country_doc_template_fields')
    op.drop_table('country_doc_template_fields')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_branch_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_academic_qualifications_tenant_id'), table_name='academic_qualifications')
    op.drop_index(op.f('ix_academic_qualifications_id'), table_name='academic_qualifications')
    op.drop_table('academic_qualifications')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_tenant_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_test_types_id'), table_name='test_types')
    op.drop_table('test_types')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_index(op.f('ix_students_letzstudy_email'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_branch_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_record_stage_history_workflow_id'), table_name='record_stage_history')
    op.drop_index(op.f('ix_record_stage_history_tenant_id'), table_name='record_stage_history')
    op.drop_index(op.f('ix_record_stage_history_record_id'), table_name='record_stage_history')
    op.drop_index(op.f('ix_record_stage_history_id'), table_name='record_stage_history')
    op.drop_table('record_stage_history')
    op.drop_index(op.f('ix_enquiry_students_tenant_id'), table_name='enquiry_students')
    op.drop_index(op.f('ix_enquiry_students_name'), table_name='enquiry_students')
    op.drop_index(op.f('ix_enquiry_students_intake_year'), table_name='enquiry_students')
    op.drop_index(op.f('ix_enquiry_students_intake_month'), table_name='enquiry_students')
    op.drop_index(op.f('ix_enquiry_students_id'), table_name='enquiry_students')
    op.drop_table('enquiry_students')
    op.drop_index(op.f('ix_country_doc_templates_tenant_id'), table_name='country_doc_templates')
    op.drop_index(op.f('ix_country_doc_templates_id'), table_name='country_doc_templates')
    op.drop_index(op.f('ix_country_doc_templates_country'), table_name='country_doc_templates')
    op.drop_table('country_doc_templates')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workflow_stages_workflow_id'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_tenant_id'), table_name='workflow_stages')
    op.drop_index(op.f('ix_workflow_stages_id'), table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_form_fields_tenant_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_form_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_field_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_custom_field_values_tenant_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_record_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_id'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_field_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_universities_tenant_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_forms_tenant_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_custom_fields_tenant_id'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_id'), table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
